projet:
    path:     /
    defaults: { _controller: ProjetBundle:Projet:index }

projet_details:
    path:     /{slugProjet}
    defaults: { _controller: ProjetBundle:Projet:details }
    requirements:
      lensModel: '[a-zA-Z0-9-_\/-\s.]+'

projet_ajout:
    path:     /ajout
    defaults: { _controller: ProjetBundle:ModalProjet:ajoutProjet }
    options:
        expose: true

projet_supprimer:
    path:     /suppression
    defaults: { _controller: ProjetBundle:ModalProjet:supprimerProjet}
    options:
        expose: true

projet_get:
    path:     /get
    defaults: { _controller: ProjetBundle:ModalProjet:getProjet}
    options:
        expose: true

projet_modif:
    path:     /modif
    defaults: { _controller: ProjetBundle:ModalProjet:modifProjet}
    options:
        expose: true