<?php

namespace Projet\ProjetBundle\Repository;

/**
 * ProjetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjetRepository extends \Doctrine\ORM\EntityRepository
{
    public function mesProjets($userId){
        $req = $this->createQueryBuilder('p')

            ->select('p')
            ->leftJoin('p.team','t')
            ->where('p.User  = :userConnecte')
            ->orWhere('t.id  = :userConnecte')
            ->setParameter('userConnecte', $userId)
            ->orderBy('p.dateAjoutProjet', 'DESC');

        return $req->getQuery()->getResult();
    }


}
